


spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: '000000'
      url: jdbc:mysql://127.0.0.1:3306/mp?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
  thymeleaf:
    servlet:
      content-type:


mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field:
